# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eWJrQHYPLCdL4u6lG3MbEHbJwl_FZF7h
"""

from scapy.all import *
import os

# Callback function to process captured packets
def packet_callback(packet):
    print(f"Packet Captured: {packet.summary()}")
    if packet.haslayer(IP):
        ip_src = packet[IP].src
        ip_dst = packet[IP].dst
        print(f"Source IP: {ip_src} -> Destination IP: {ip_dst}")
        if packet.haslayer(TCP):
            print(f"Protocol: TCP, Source Port: {packet[TCP].sport} -> Destination Port: {packet[TCP].dport}")
        elif packet.haslayer(UDP):
            print(f"Protocol: UDP, Source Port: {packet[UDP].sport} -> Destination Port: {packet[UDP].dport}")

# Start the packet sniffer
def start_sniffer():
    print("Starting packet capture...")
    sniff(prn=packet_callback, store=0)

# Run the sniffer
if _name_ == "_main_":
    start_sniffer()